config/routes.rb
Rails.application.routes.draw do
  
  get '/index', to: 'users#showcase', as: 'index'
  get '/signin', to: 'users#signin', as: 'signin'
  get '*missing', to: 'users#default'

  post '/signin', to: 'users#create'
  post '/login', to: 'sessions#create'
  post '/index', to: 'users#calculate'

  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bmi_table.rb
class BmiTable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_password :recovery_password, validations: false
  validates :names, :surnames, :email, :password, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/' unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
  end
  
  def login
  end

  def create
    @user = User.find_by email: user_params[:email]

    if @user and  @user.authenticate(user_params[:password]) 
      session[:user_id] = @user.id
      redirect_to '/index'
    else
      redirect_to '/'
    end

  end

  def destroy
    session.delete(:user_id)
    @user = nil
    redirect_to '/'
  end

  private 
  def user_params
    params.require(:user).permit(:names, :surnames, :email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:login,:signin,:create, :default]
  def login
    @user = User.new
  end

  def signin
    @user = User.new
  end

  def showcase
  end

  def create

    @user = User.new(user_params)
    @user.email.downcase!

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/index'
    else
      render 'signin'
    end
  end


  def calculate
    height = bmi_params[:height].to_f
    weight = bmi_params[:weight].to_f
    @message = ""

    if height == 0 || weight == 0
      @message = "Please insert valid numbers"
    else
      bmi = (weight / height ** 2).round(1)
      category = BmiTable.where("bmi_from <= #{bmi}").order(created_at: :desc).first
      @message = "You have a BMI of #{bmi}. Category: #{category[:category]}" 
    end

    render 'showcase' 
  end

  def default
  end

  private 
  def user_params
    params.require(:user).permit(:names, :surnames, :email, :password)
  end

  def bmi_params
    params.require(:bmi).permit(:height, :weight)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BMI Calculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/icon?family=Material\Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/default.html.erb
    <div class="center-align card-panel red accent-4 white-text">
      <h1>ERROR 404</h1>
      <p>
        The route typed not exists, please verify if its correct.
      </p>
    </div>

app/views/users/login.html.erb
<div class = "container">
  <div class="center-align">
    <h1>BMI Calculator</h1>
    <h5>Sign with us and get your BMI index</h5>
  </div>

  <%= form_with scope: :user, url: '/login', local: true do |form| %>

    <% if @user.errors.any?%>
      <div class="error">
        <h2>
          <%= pluralize(@user.errors.count, "error")%>
          Something happened wrong trying to Log In.
        </h2>

        <ul>
          <% @user.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
        <%end%>
        </ul>
      </div>
    <%end%>

    <p>
      <%= form.label :email %>
      <%= form.email_field :email %>
    </p>

    <p>
      <%= form.label :password%>
      <%= form.password_field :password%>
    </p>
    <button class="btn light-green accent-4 hoverable", type="submit">
      Log In
    </button>
  <%end%>

  <%= link_to 'SignIn if you have not an account yet', signin_path%>
</div>

app/views/users/showcase.html.erb
<% if logged_in? %>
  <div class="container">

    <%= link_to 'Log out', '/logout', method: :delete%>

    <div class="center-align">
      <h2>Calculates your Body Mass Index (BMI)</h2>
      <h6> Just input your height (in meters) and your weight (in kilogrames) </h6>
    </div>

    <%= form_with scope: :bmi, url: '/index' ,local: true do |form| %>
      <p>
      <%= form.label :height %>
      <%= form.text_field :height %>
      </p>

      <p>
      <%= form.label :weight%>
      <%= form.text_field :weight%>
      </p>

      <button class="btn indigo darken-4 hoverable">
        Calculate BMI
      </button>
    <%end%>

    <label class="black-text"><%= @message%></label>
  </div>
<%end%>

app/views/users/signin.html.erb
<div class="container">
  <div class="center-align"> 
    <h1> Sign Up </h1>

    <h6>
      Sign up with us to get your Body Mass Index (BMI).
    </h6>
  </div>

  <div class="row">
    <form class="col s12">
    </form>
  </div>

  <%= form_with scope: :user, url: '/signin', local: true do |form|%>

    <% if @user.errors.any? %>
      <div id="errors" class="card-panel center-align red accent-4 white-text">
        <h6>
          <%= pluralize(@user.errors.count, "error")%>
          Something wrong happened from being registered:
        </h6>

        <ul>
          <% @user.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
          <%end%>
        </ul>
      </div>
    <%end%>

    <p>
      <%= form.label :names, 'Name(s):'%>
      <%= form.text_field :names %>
    </p>

    <p>
      <%= form.label :surnames, 'Surname(s):'%>
      <%= form.text_field :surnames %>
    </p>

    <p>
      <%= form.label :email, 'Email:'%>
      <%= form.email_field :email %>
    </p>

    <p>
      <%= form.label :password, 'Password:'%>
      <%= form.password_field :password %>
    </p>

    <button class="btn indigo darken-4 hoverable", type="submit">
      Sign Up
    </button>
  <%end%>

  <%= link_to 'Go Back', '/'%>
</div>